using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Media_Bazaar
{
    public class AutoGeneratePassword
    {
        private PasswordGenerator passwordGenerator = new PasswordGenerator();

        public string autoGeneratePassword()
        {
            List<string> password = new List<string>();
            //the autogenerated password will have 8characters(containing symbols)
            password = passwordGenerator.GeneratePasswords(8, 1, true);
            foreach (string pass in password)
            {
                return pass;
            }
            return null;
        }
    }
}
